[build]
rustflags = ["-C", "target-cpu=native"]

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=-avx,-avx2"]

[alias]
xtask = "run --manifest-path xtask/Cargo.toml --"
xtask5 = "run --manifest-path xtask5/Cargo.toml --"
xtask6 = "run --manifest-path xtask6/Cargo.toml --"